Add password authentication to KeepalivedGroup
redhat-cop/keepalived-operator pull request #57
Opened 2021-03-06 00:16 UTC by tommasopozzetti

As requested in #48, this PR introduces the ability to set up password authentication for VRRP instances. The configuration is global at the KeepalivedGroup level, therefore all VRRP instances managed by pod in the given KeepalivedGroup will share the same password.

The password can be specified via a secret that can be referenced in the KeepalivedGroup CR as follows:
```yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: KeepalivedGroup
metadata:
  name: keepalivedgroup-router
spec:
  image: registry.redhat.io/openshift4/ose-keepalived-ipfailover
  interface: ens3
  nodeSelector:
    node-role.kubernetes.io/loadbalancer: ""
  passwordAuth:
    secretRef:
      name: my-secret
    secretKey: vrrpPass
---

apiVersion: v1
kind: Secret
metadata:
  name: my-secret
stringData:
  vrrpPass: 1234
```
The `secretKey` value is not mandatory and defaults to `password` if not specified.

2021-03-06 03:11 UTC, raffaelespazzoli requested changes

2021-03-06 03:11 UTC, raffaelespazzoli commented on controllers/keepalivedgroup_controller.go
> +			// Requeue and log error
please follow the pattern for the other error management code blocks, ie:
1. log the error
2.  return with the manage error function.

2021-03-06 03:11 UTC, raffaelespazzoli commented on controllers/keepalivedgroup_controller.go
> +			// Requeue and log error
same as above.

2021-03-08 16:57 UTC, tommasopozzetti commented
@raffaelespazzoli thanks for reviewing this.
I have changed the error handling to conform to the suggested pattern.

2021-03-18 19:08 UTC, David-Igou commented
LGTM

2021-03-18 19:08 UTC, merged